[project]
name = "nfl-prop-hunter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.14"
dependencies = [
    "nflreadpy>=0.1.5",
    "plotly>=6.5.0",
    "polars>=1.35.2",
    "streamlit>=1.51.0",
]
